apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: delay
          image: busybox
          command: ['nslookup', 'web-svc.default.svc.cluster.local']
      containers:
        - name: webserver
          image: nginx:1.14.2
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  selector:
    app: nginx
  ports:
    - name: web-svc-port
      port: 80
      protocol: TCP
      targetPort: 80