---
  - name: clickhouse-role
#    src: git@github.com:danilabar/clickhouse-role.git
    src: git@github.com:kutorol/clickhouse-role-2.git
    scm: git
    version: "0.1.0"
  - name: vector-role
#    src: git@github.com:danilabar/vector-role.git
    src: git@github.com:kutorol/vector-role-2.git
    scm: git
    version: "0.1.0"
  - name: lighthouse-role
#    src: git@github.com:danilabar/lighthouse-role.git
    src: git@github.com:kutorol/lighthouse-role-2.git
    scm: git
    version: "0.1.0"
