apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: webserver
          image: nginx:1.14.2
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          imagePullPolicy: IfNotPresent
        - name: multitool-web
          image: wbitt/network-multitool
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "1443"

---

apiVersion: v1
kind: Service
metadata:
  name: netology-svc-deploy
spec:
  selector:
    app: nginx
  ports:
    - name: web-netology-deploy
      port: 9001
      targetPort: 80
    - name: web-netology-multi
      port: 9002
      targetPort: 8080


---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: custom-multi
spec:
  containers:
    - name: multitool-web-custom
      image: wbitt/network-multitool
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080

