apiVersion: v1
kind: Service
metadata:
  name: netology-svc-deploy-local
spec:
  selector:
    app: nginx
  ports:
    - name: web-netology-deploy-local
      port: 80
      nodePort: 30041
    - name: web-netology-multi-local
      port: 8080
      nodePort: 30042
  type: NodePort
